name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Package fatjar with assembly plugin
      run: sbt assembly
    - name: Upload jar file
      uses: actions/upload-artifact@v1
      with:
        name: dsti-samples-assembly.jar
        path: target/scala-2.12/spark-sbt-template-assembly-1.0.jar
